[tool.poetry]
name = "leetcode"
version = "0.1.0"
description = ""
authors = ["teamofroman <rsateam@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
sortedcontainers = "^2.4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
